[package]
name = "hermes_comments"
version = "0.1.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hermes_estree = { workspace = true }
hermes_parser = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_json = { workspace = true }
